name: TRME
channels:
  - defaults
dependencies:
  - absl-py
  - backcall
  - cachetools
  - charset-normalizer
  - chumpy
  - cycler
  - decorator
  - google-auth
  - google-auth-oauthlib
  - grpcio
  - idna
  - imageio
  - ipdb
  - ipython
  - ipython-genutils
  - jedi
  - joblib
  - kiwisolver
  - markdown
  - matplotlib
  - matplotlib-inline
  - oauthlib
  - pandas
  - parso
  - pexpect
  - pickleshare
  - prompt-toolkit
  - protobuf
  - ptyprocess
  - pyasn1
  - pyasn1-modules
  - pygments
  - pyparsing
  - python-dateutil
  - pytz
  - pyyaml
  - requests
  - requests-oauthlib
  - rsa
  - scikit-learn
  - scipy
  - sklearn
  - smplx
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - threadpoolctl
  - toml
  - tqdm
  - traitlets
  - urllib3
  - wcwidth
  - werkzeug
  - gdown
  - moviepy
  - git+https://github.com/openai/CLIP.git
  - git+https://github.com/nghorbani/human_body_prior
